import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export async function GET() {
    const baseUrl = 'https://taxiserviceksa.com';
    
    const routePages = [
        '/routes/abu-dhabi-dammam',
        '/routes/abu-dhabi-jeddah',
        '/routes/abu-dhabi-madinah',
        '/routes/abu-dhabi-makkah',
        '/routes/abu-dhabi-riyadh',
        '/routes/alula-jeddah',
        '/routes/amman-dammam',
        '/routes/amman-jeddah',
        '/routes/amman-madinah',
        '/routes/amman-makkah',
        '/routes/amman-riyadh',
        '/routes/bahrain-dammam',
        '/routes/bahrain-jeddah',
        '/routes/bahrain-madinah',
        '/routes/bahrain-makkah',
        '/routes/bahrain-riyadh',
        '/routes/dammam-abu-dhabi',
        '/routes/dammam-amman',
        '/routes/dammam-bahrain',
        '/routes/dammam-doha',
        '/routes/dammam-dubai',
        '/routes/dammam-kuwait',
        '/routes/dammam-muscat',
        '/routes/dammam-sharjah',
        '/routes/doha-dammam',
        '/routes/doha-jeddah',
        '/routes/doha-madinah',
        '/routes/doha-makkah',
        '/routes/doha-riyadh',
        '/routes/dubai-dammam',
        '/routes/dubai-jeddah',
        '/routes/dubai-madinah',
        '/routes/dubai-makkah',
        '/routes/dubai-riyadh',
        '/routes/jeddah-abu-dhabi',
        '/routes/jeddah-alula',
        '/routes/jeddah-amman',
        '/routes/jeddah-bahrain',
        '/routes/jeddah-doha',
        '/routes/jeddah-dubai',
        '/routes/jeddah-kuwait',
        '/routes/jeddah-madinah',
        '/routes/jeddah-makkah',
        '/routes/jeddah-makkah-old',
        '/routes/jeddah-muscat',
        '/routes/jeddah-riyadh',
        '/routes/jeddah-sharjah',
        '/routes/jeddah-taif',
        '/routes/jeddah-to-dar-al-taqwa-madinah',
        '/routes/jeddah-to-fairmont-makkah',
        '/routes/jeddah-to-hilton-madinah',
        '/routes/jeddah-to-oberoi-madinah',
        '/routes/jeddah-to-pullman-makkah',
        '/routes/jeddah-to-swissotel-makkah',
        '/routes/jeddah-train-station-taxi',
        '/routes/jeddah-yanbu',
        '/routes/kuwait-dammam',
        '/routes/kuwait-jeddah',
        '/routes/kuwait-madinah',
        '/routes/kuwait-makkah',
        '/routes/kuwait-riyadh',
        '/routes/madinah-abu-dhabi',
        '/routes/madinah-amman',
        '/routes/madinah-bahrain',
        '/routes/madinah-doha',
        '/routes/madinah-dubai',
        '/routes/madinah-jeddah',
        '/routes/madinah-kuwait',
        '/routes/madinah-makkah',
        '/routes/madinah-muscat',
        '/routes/madinah-sharjah',
        '/routes/madinah-to-jeddah-airport-departures',
        '/routes/madinah-train-station-taxi',
        '/routes/makkah-abu-dhabi',
        '/routes/makkah-amman',
        '/routes/makkah-bahrain',
        '/routes/makkah-doha',
        '/routes/makkah-dubai',
        '/routes/makkah-jeddah',
        '/routes/makkah-kuwait',
        '/routes/makkah-madinah',
        '/routes/makkah-muscat',
        '/routes/makkah-sharjah',
        '/routes/muscat-dammam',
        '/routes/muscat-jeddah',
        '/routes/muscat-madinah',
        '/routes/muscat-makkah',
        '/routes/muscat-riyadh',
        '/routes/riyadh-abu-dhabi',
        '/routes/riyadh-amman',
        '/routes/riyadh-bahrain',
        '/routes/riyadh-dammam',
        '/routes/riyadh-doha',
        '/routes/riyadh-dubai',
        '/routes/riyadh-jeddah',
        '/routes/riyadh-kuwait',
        '/routes/riyadh-makkah',
        '/routes/riyadh-muscat',
        '/routes/riyadh-sharjah',
        '/routes/sharjah-dammam',
        '/routes/sharjah-jeddah',
        '/routes/sharjah-madinah',
        '/routes/sharjah-makkah',
        '/routes/sharjah-riyadh',
        '/routes/tabuk-abha',
        '/routes/tabuk-abu-arish',
        '/routes/tabuk-afif',
        '/routes/tabuk-al-bad',
        '/routes/tabuk-al-badai',
        '/routes/tabuk-al-bahah',
        '/routes/tabuk-al-bukayriyah',
        '/routes/tabuk-al-ghat',
        '/routes/tabuk-al-jafr',
        '/routes/tabuk-al-khafji',
        '/routes/tabuk-al-kharj',
        '/routes/tabuk-al-khobar',
        '/routes/tabuk-al-lith',
        '/routes/tabuk-al-majardah',
        '/routes/tabuk-al-majmaah',
        '/routes/tabuk-al-makhwah',
        '/routes/tabuk-al-midhnab',
        '/routes/tabuk-al-mubarraz',
        '/routes/tabuk-al-muzahmiyya',
        '/routes/tabuk-al-nairyah',
        '/routes/tabuk-al-namas',
        '/routes/tabuk-al-qunfudhah',
        '/routes/tabuk-al-quwayiyah',
        '/routes/tabuk-al-rais',
        '/routes/tabuk-al-rass',
        '/routes/tabuk-al-uyun',
        '/routes/tabuk-al-wajh',
        '/routes/tabuk-alula',
        '/routes/tabuk-arar',
        '/routes/tabuk-baljurashi',
        '/routes/tabuk-bareq',
        '/routes/tabuk-bishah',
        '/routes/tabuk-buqayq',
        '/routes/tabuk-buraidah',
        '/routes/tabuk-dammam',
        '/routes/tabuk-dariya',
        '/routes/tabuk-dawadmi',
        '/routes/tabuk-dhahban',
        '/routes/tabuk-duba',
        '/routes/tabuk-hafar-al-batin',
        '/routes/tabuk-hail',
        '/routes/tabuk-haql',
        '/routes/tabuk-hofuf',
        '/routes/tabuk-huraymila',
        '/routes/tabuk-jeddah',
        '/routes/tabuk-jizan',
        '/routes/tabuk-jubail',
        '/routes/tabuk-kaec',
        '/routes/tabuk-khafji',
        '/routes/tabuk-khulais',
        '/routes/tabuk-madinah',
        '/routes/tabuk-magna',
        '/routes/tabuk-mahad-al-dhahab',
        '/routes/tabuk-makkah',
        '/routes/tabuk-masturah',
        '/routes/tabuk-najran',
        '/routes/tabuk-neom',
        '/routes/tabuk-qilwah',
        '/routes/tabuk-qurayyat',
        '/routes/tabuk-rabigh',
        '/routes/tabuk-riyadh',
        '/routes/tabuk-rumah',
        '/routes/tabuk-sabya',
        '/routes/tabuk-sakaka',
        '/routes/tabuk-samtah',
        '/routes/tabuk-sharma',
        '/routes/tabuk-sharurah',
        '/routes/tabuk-taif',
        '/routes/tabuk-tanuma',
        '/routes/tabuk-tayma',
        '/routes/tabuk-thadiq',
        '/routes/tabuk-thuwal',
        '/routes/tabuk-turaif',
        '/routes/tabuk-umluj',
        '/routes/tabuk-unaizah',
        '/routes/tabuk-wadi-ad-dawasir',
        '/routes/tabuk-yanbu',
        '/routes/tabuk-zulfi',
        '/routes/taif-jeddah',
        '/routes/yanbu-jeddah',
    ];

    const routeUrls = routePages.map((route) => {
        return `  <url>
    <loc>${baseUrl}${route}/</loc>
    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>`;
    }).join('\n');

    const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${routeUrls}
</urlset>`;

    return new NextResponse(sitemap, {
        status: 200,
        headers: {
            'Content-Type': 'application/xml',
            'Cache-Control': 'public, max-age=86400, s-maxage=86400',
        },
    });
}

